default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: lucas
  password: <%= ENV["DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: leilao_development

test:
  <<: *default
  database: leilao_test

production:
  <<: *default
  database: leilao_production
